### PR TITLE
Added ability to exclude disabled products during import.

### LINKED ISSUE #61: Import only Enabled Products
This is more of a feature request really, but I suggest that the default behavior only import Enabled products from Magento. I don't know what kind of impact this will have on VSF, but my basic understanding of it so leads me to believe importing disabled products is unnecessary and only increases the size of the Elastic Search index.

Most Magento shops I have worked on seem to have a constant cycle of products that are enabled/disabled based on needs, stock, seasons, etc... By filtering the disabled products out it can decrease the sync time and the index size.

Let me know your thoughts, and if you have any concerns with this approach.

### PR DESCRIPTION
**Pull request by rain2o**
Closes #61 

Added config/env variable check before adding filter. Defaults to false (meaning default behavior is to import all products). 

I was going to add some info in the README but wasn't positive where the best location was. 

I also did a small code refactor in this function where the api is constructed to make it a little cleaner.

### CODE REVIEW

**Comment by pkarw** [comment]
Can You please just resolve the conflicts before I will merge this in?

**Comment by rain2o** [comment]
Conflict resolved and added a note to the README.

**Comment by rain2o** [comment]
I just noticed my last commit with the README changes didn't push successfully the first time! Should I submit a 2nd PR with that change now that this one is closed?

**Comment by pkarw** [comment]
No worries. Please just submit the second PR; thanks!

**Pull request merged**
