### PR TITLE
Fix wrong type coercion for bool commandline options

### PR DESCRIPTION
**Pull request by revlis-x**
Fix for #53. 
Correct way is to default to false for all boolean options and drop `= true` from commandline option, since this is always interpreted as a string by commander. I know this calls for a lot of adjustments in documentation. Also mage2vs.js in vue-storefront-api would need updating. I can provide a PR for that.
Other solution would be to typecast inside cli.js but that woud create overhead where it is not neccessary.

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks for this PR. I would prefer the solution that doesn't require to change all the docs as it's pretty widely spread. Can You please modify it todo the typecast instead?

**Comment by pkarw** [comment]
Would be awesome if You can modify it before Thursday as we planned 1.6 release on 6th of December

**Comment by revlis-x** [comment]
I did the requested changes. Command-line syntax is untouched and fully backwards compatible.

**Comment by pkarw** [comment]
I think it may be safer to use "JSON.parse(removeNonExistent)" as it will work with: true, 1 ... etc wdyt?

**Comment by pkarw** [comment]
... either sth like:

```
stringToBoolean: function(string){
    switch(string.toLowerCase().trim()){
        case "true": case "yes": case "1": return true;
        case "false": case "no": case "0": case null: return false;
        default: return Boolean(string);
    }
}
```

**Comment by revlis-x** [comment]
JSON.parse does not like to be fed with random strings and your second suggestion still returns the input as string, when no case matches, so it can still lead to undesired behaviour. We could default to false here, but I personally do not see the gain here to provide these "faux bool" options which are unneccessary to begin with.

Could do it anyway, if you prefer it that way.

**Comment by pkarw** [comment]
OK, I got it. I'll take it as it is then

**Pull request merged**
