### PR TITLE
product attributes now mapping as array

### PR DESCRIPTION
**Pull request by BartoszLiburski**
product attributes now mapping as array if attribute is a string containing numbers separated by comma

### CODE REVIEW

**Comment by pkarw** [comment]
@BartoszLiburski can You please solve the conflicts?

**Comment by pkarw** [comment]
@BartoszLiburski is this PR still valid? As far as I remember we already solved multi attributes other way? Correct?

**Comment by DaanKouters** [comment]
Is it possible that this PR gets merged to Mage2vs?
It's needed for querying ES with multiple option id's per filter, something that we use in our module:
https://github.com/GetNoticedNL/vsf-layered-navigation

I believe merging this, doesn't break code in VSF core. But that's needed to be verified of course.

**Comment by pkarw** [comment]
What do You think on simplyfying It a little bit as proposed in the CR comments? Could you take care of the proposed changes @DaanKouters

**Comment by DaanKouters** [comment]
@pkarw yeah i can do that. It only concerns the custom attributes from product and those of the child products.

This for loop from line 212 - 226: https://github.com/DivanteLtd/mage2vuestorefront/blob/1c7f216ef732abd3fdb7f5c5fe336db2036cb06a/src/adapters/magento/product.js

takes care of this

It should also be done for the child products. What needs to be done is make a function of this and use this in the preprocessing of the items in the product adapter.

Correct me if i'm wrong :)

**Comment by pkarw** [comment]
You’re right :-)

**Comment by DaanKouters** [comment]
Alrighty, no problem. i'll do this next week

**Comment by MoizurRehman** [comment]
is vsf-layered-navigation support in vuetique them?

**Comment by DaanKouters** [comment]
> is vsf-layered-navigation supports in vuetique them?

hi, it should be in VSF 1.10.5
For theme integration you need to take care of the right components (f.e. sidebar and active filters) and to use the methods in your Category page in Vuetique theme which are provided in the theme-integration/pages/Category.vue file.

If you need any help for implementing it, let me know

**Comment by PandaTawer3** [comment]
@DaanKouters Hello are you can help me? I need to add filter by category.
Something like this.
0cc9af7f-69bf-4488-86e7-73e667e1cadc

**Pull request merged**
